# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Maintainer: David McFarland <corngood@gmail.com>
# Autogenerated from AMD's Packages file

pkgbase=amdgpu-pro-installer
pkgname=(amdgpu amdgpu-core amdgpu-dkms amdgpu-libgl amdgpu-pro amdgpu-pro-core amf-amdgpu-pro gst-omx-amdgpu lib32-amdgpu-libgl lib32-amdgpu-pro lib32-gst-omx-amdgpu lib32-libdrm-amdgpu lib32-llvm-amdgpu lib32-mesa-amdgpu lib32-opencl-amdgpu lib32-opencl-orca-amdgpu lib32-vulkan-amdgpu lib32-wayland-amdgpu lib32-wsa-amdgpu lib32-xserver-xorg-amdgpu-video-amdgpu libdrm-amdgpu llvm-amdgpu mesa-amdgpu opencl-amdgpu opencl-orca-amdgpu vulkan-amdgpu wayland-amdgpu wayland-protocols-amdgpu wsa-amdgpu xf86-video-amdgpu-pro xserver-xorg-amdgpu)
pkgver=18.50.725072
pkgrel=1
arch=('x86_64')
url='http://www.amd.com'
license=('custom:AMD')
makedepends=('wget')

DLAGENTS='https::/usr/bin/wget --referer https://www.amd.com/ru/support/kb/release-notes/rn-rad-lin-18-50-unified -N %u'

source=(https://drivers.amd.com/drivers/linux/amdgpu-pro-18.50-725072-ubuntu-18.04.tar.xz
	0001-disable-firmware-copy.patch
	0002-Adding-arch-option-in-makefile.patch)
sha256sums=(52a2c1f1120edb564d5af2535439e0e7d2b3815cab457374b921687f3fd9a21a
	252d28b86ab878a90d564e1a29baf5644ea8c9e47e76bc8395928c092360cf85
	d14285e05e3c98eece1fb75a7a255431d351415f9b256174e48fc10a883181a9)



# extracts a debian package
# $1: deb file to extract
extract_deb() {
	local tmpdir="$(basename "${1%.deb}")"
	rm -Rf "$tmpdir"
	mkdir "$tmpdir"
	cd "$tmpdir"
	ar x "$1"
	tar -C "${pkgdir}" -xf data.tar.xz
}
# move ubuntu specific /usr/lib/x86_64-linux-gnu to /usr/lib
# $1: library dir
# $2: destination (optional)
move_libdir() {
	local libdir="usr/lib"
	if [ -n "$2" ]; then
		libdir="$2"
	fi
	if [ -d "$1" ]; then
		if [ -d "${pkgdir}/${libdir}" ]; then
			cp -ar -t "${pkgdir}/${libdir}/" "$1"/*
			rm -rf "$1"
		else
			mkdir -p "${pkgdir}/${libdir}"
			mv -t "${pkgdir}/${libdir}/" "$1"/*
			rmdir "$1"
		fi
	fi
}


package_amdgpu () {
	pkgdesc="Meta package to install amdgpu userspace components"
	arch=('x86_64')
	depends=()

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-lib_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-lib32_18.50-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

}


package_amdgpu-core () {
	pkgdesc="Core meta package for unified amdgpu driver."
	install=amdgpu-core.install
	arch=('any')
	depends=('amdgpu-dkms' )

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-core_18.50-725072_all.deb

	move_libdir "${pkgdir}/lib"

}


package_amdgpu-dkms () {
	pkgdesc="The AMDGPU Pro kernel module"
	arch=('any')
	provides=('amdgpu=18.50')
	depends=('amdgpu-core=18.50.725072-1' 'dkms>=1.95')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-dkms_18.50-725072_all.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	msg 'Applying patches...'
	(cd ${pkgdir}/usr/src/amdgpu-18.50-725072;
		sed -i 's/\/extra/\/extramodules/' dkms.conf
			msg2 '0001-disable-firmware-copy.patch'
		patch -p1 -i "${srcdir}/0001-disable-firmware-copy.patch";
		msg2 '0002-Adding-arch-option-in-makefile.patch'
		patch -p1 -i "${srcdir}/0002-Adding-arch-option-in-makefile.patch"
	)
}


package_amdgpu-libgl () {
	pkgdesc="free implementation of the OpenGL API -- GLX development files"
	arch=('x86_64')
	provides=('libgl' 'libegl' 'libgles')
	conflicts=('libgl' 'libegl' 'libgles' 'libglvnd')
	depends=('amdgpu-pro-core=18.50.725072-1' 'libdrm-amdgpu=18.50.725072-1' 'libx11' 'libx11>=1.4.99.1' 'libxcb' 'libxcb>=1.8' 'libxcb>=1.9.2' 'libxdamage>=1.1' 'libxext' 'libxfixes' 'libxshmfence' 'libxxf86vm' 'wayland-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-appprofiles_18.50-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-dri_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-ext_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-glx_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libglapi1-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-pro_18.50-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	mkdir -p "${pkgdir}"/usr/lib/dri/
	mkdir -p "${pkgdir}"/usr/lib/xorg/modules/extensions/
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libEGL.so "${pkgdir}"/usr/lib/libEGL.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libEGL.so.1 "${pkgdir}"/usr/lib/libEGL.so.1
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so "${pkgdir}"/usr/lib/libGL.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1 "${pkgdir}"/usr/lib/libGL.so.1
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGL.so.1.2 "${pkgdir}"/usr/lib/libGL.so.1.2
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGLESv2.so "${pkgdir}"/usr/lib/libGLESv2.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libGLESv2.so.2 "${pkgdir}"/usr/lib/libGLESv2.so.2
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libglapi.so "${pkgdir}"/usr/lib/libglapi.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libglapi.so.1 "${pkgdir}"/usr/lib/libglapi.so.1
	ln -s /opt/amdgpu-pro/lib/xorg/modules/extensions/libglx.so "${pkgdir}"/usr/lib/xorg/modules/extensions/libglx.so
	# This is needed because libglx.so has a hardcoded DRI_DRIVER_PATH
	mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/dri ${pkgdir}/usr/lib/
	ln -s /usr/lib/dri ${pkgdir}/usr/lib/x86_64-linux-gnu/dri
	mkdir -p "${pkgdir}/etc/ld.so.conf.d/"
	echo "/opt/amdgpu-pro/lib/x86_64-linux-gnu/" > "${pkgdir}"/etc/ld.so.conf.d/amdgpu-pro.conf
}


package_amdgpu-pro () {
	pkgdesc="Meta package to install amdgpu Pro components"
	arch=('any')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-dkms=18.50.725072-1' 'amdgpu-libgl=18.50.725072-1' 'amdgpu=18.50.725072-1' 'lib32-amdgpu-libgl=18.50.725072-1' 'lib32-mesa-amdgpu=18.50.725072-1' 'libelf' 'mesa-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-doc_18.50-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-pro-lib32_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-pro-pin_18.50-725072_all.deb

	move_libdir "${pkgdir}/lib"

}


package_amdgpu-pro-core () {
	pkgdesc="Core meta package for unified amdgpu driver."
	arch=('any')
	depends=('amdgpu-core=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-pro-core_18.50-725072_all.deb

	move_libdir "${pkgdir}/lib"

}


package_amf-amdgpu-pro () {
	pkgdesc="AMDGPU Pro Advanced Multimedia Framework"
	arch=('x86_64')
	depends=('libgl' 'libx11' 'mesa-amdgpu=18.50.725072-1' 'opencl-amdgpu=18.50.725072-1' 'vulkan-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amf-amdgpu-pro_1.4.11-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

}


package_gst-omx-amdgpu () {
	pkgdesc="GStreamer OpenMAX plugins for AMDGPU Pro"
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'glib2>=2.37.3' 'gst-plugins-base>=1.6.0' 'gstreamer>=1.0.0' 'libomxil-bellagio')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./gst-omx-amdgpu_1.0.0.1-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/gstreamer-1.0/
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/gstreamer-1.0/libgstomx.so "${pkgdir}"/usr/lib/gstreamer-1.0/libgstomx.so
}


package_lib32-amdgpu-libgl () {
	pkgdesc="free implementation of the OpenGL API -- GLX development files 32 bit"
	arch=('x86_64')
	provides=('lib32-libgl' 'lib32-libgles' 'lib32-libegl')
	conflicts=('lib32-libgl' 'lib32-libgles' 'lib32-libegl' 'lib32-libglvnd')
	depends=('amdgpu-libgl=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'lib32-libx11' 'lib32-libx11>=1.4.99.1' 'lib32-libxcb' 'lib32-libxcb>=1.8' 'lib32-libxcb>=1.9.2' 'lib32-libxdamage>=1.1' 'lib32-libxext' 'lib32-libxfixes' 'lib32-libxshmfence' 'lib32-libxxf86vm' 'libdrm-amdgpu=18.50.725072-1' 'wayland-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-pro_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-dri_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-ext_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-pro-glx_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libglapi1-amdgpu-pro_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-pro_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib32/
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libEGL.so "${pkgdir}"/usr/lib32/libEGL.so
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libEGL.so.1 "${pkgdir}"/usr/lib32/libEGL.so.1
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGL.so "${pkgdir}"/usr/lib32/libGL.so
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGL.so.1 "${pkgdir}"/usr/lib32/libGL.so.1
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGLESv2.so "${pkgdir}"/usr/lib32/libGLESv2.so
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libGLESv2.so.2 "${pkgdir}"/usr/lib32/libGLESv2.so.2
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libglapi.so "${pkgdir}"/usr/lib32/libglapi.so
	ln -s /opt/amdgpu-pro/lib/i386-linux-gnu/libglapi.so.1 "${pkgdir}"/usr/lib32/libglapi.so.1
	mv "${pkgdir}"/usr/lib/i386-linux-gnu/dri ${pkgdir}/usr/lib32/
	ln -s /usr/lib32/dri ${pkgdir}/usr/lib/i386-linux-gnu/dri

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-amdgpu-pro () {
	pkgdesc="The AMDGPU Pro driver package 32bit"
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-dkms=18.50.725072-1' 'amdgpu-libgl=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'amdgpu-pro=18.50.725072-1' 'amdgpu=18.50.725072-1' 'gst-omx-amdgpu=18.50.725072-1' 'lib32-libdrm' 'lib32-libelf' 'libdrm-amdgpu=18.50.725072-1' 'llvm-amdgpu=18.50.725072-1' 'mesa-amdgpu=18.50.725072-1' 'wayland-amdgpu=18.50.725072-1' 'xf86-video-amdgpu-pro=18.50.725072-1' 'xserver-xorg-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-lib_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./amdgpu-pro_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-gst-omx-amdgpu () {
	pkgdesc="GStreamer OpenMAX plugins for AMDGPU Pro 32bit"
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'lib32-glib2>=2.37.3' 'lib32-gst-plugins-base>=1.6.0' 'lib32-gstreamer>=1.0.0' 'lib32-libomxil-bellagio')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./gst-omx-amdgpu_1.0.0.1-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	rm -f "${pkgdir}"/etc/xdg/gstomx.conf

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-libdrm-amdgpu () {
	pkgdesc="The AMDGPU Pro userspace interface to kernel DRM services 32 bit"
	arch=('x86_64')
	provides=('lib32-libdrm')
	conflicts=('lib32-libdrm')
	depends=('amdgpu-core=18.50.725072-1' 'libdrm-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-amdgpu1_2.4.95-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-dev_2.4.95-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-radeon1_2.4.95-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm2-amdgpu_2.4.95-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm.so "${pkgdir}"/usr/lib32/libdrm.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm.so.2 "${pkgdir}"/usr/lib32/libdrm.so.2
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm.so.2.4.0 "${pkgdir}"/usr/lib32/libdrm.so.2.4.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libkms.so "${pkgdir}"/usr/lib32/libkms.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libkms.so.1 "${pkgdir}"/usr/lib32/libkms.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libkms.so.1.0.0 "${pkgdir}"/usr/lib32/libkms.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_amdgpu.so "${pkgdir}"/usr/lib32/libdrm_amdgpu.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_amdgpu.so.1 "${pkgdir}"/usr/lib32/libdrm_amdgpu.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_amdgpu.so.1.0.0 "${pkgdir}"/usr/lib32/libdrm_amdgpu.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_radeon.so "${pkgdir}"/usr/lib32/libdrm_radeon.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_radeon.so.1 "${pkgdir}"/usr/lib32/libdrm_radeon.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libdrm_radeon.so.1.0.1 "${pkgdir}"/usr/lib32/libdrm_radeon.so.1.0.1

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-llvm-amdgpu () {
	pkgdesc="Generic buffer management API 32 bit"
	arch=('x86_64')
	provides=('lib32-llvm-libs' 'lib32-llvm')
	conflicts=('lib32-llvm' 'lib32-llvm-libs')
	depends=('amdgpu-core=18.50.725072-1' 'binfmt-support' 'lib32-libedit' 'lib32-libedit>=2.11-20080614' 'lib32-libffi>=3.0.9' 'lib32-ncurses' 'lib32-ncurses5-compat-libs>=6' 'lib32-zlib>=1.2.0' 'llvm-amdgpu=18.50.725072-1' 'python2')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libllvm7.0-amdgpu_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0-dev_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0-runtime_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-dev_7.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-runtime_7.0-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib32/
	ln -s /opt/amdgpu/lib/i386-linux-gnu/BugpointPasses.so "${pkgdir}"/usr/lib32/BugpointPasses.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libLLVM-7.0.1.so "${pkgdir}"/usr/lib32/libLLVM-7.0.1.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libLLVM-7.so "${pkgdir}"/usr/lib32/libLLVM-7.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libLLVM.so "${pkgdir}"/usr/lib32/libLLVM.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libLTO.so "${pkgdir}"/usr/lib32/libLTO.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libLTO.so.7 "${pkgdir}"/usr/lib32/libLTO.so.7
	ln -s /opt/amdgpu/lib/i386-linux-gnu/LLVMHello.so "${pkgdir}"/usr/lib32/LLVMHello.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/TestPlugin.so "${pkgdir}"/usr/lib32/TestPlugin.so
	ln -s /usr/lib32/libedit.so "${pkgdir}"/usr/lib32/libedit.so.2

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-mesa-amdgpu () {
	pkgdesc="Mesa implementation for AMDGPU Pro. Contains 32 bit libs"
	arch=('x86_64')
	provides=('lib32-mesa-libgl' 'lib32-mesa-dri' 'lib32-opengl-driver' 'osmesa' 'lib32-mesa')
	conflicts=('lib32-mesa-dri' 'lib32-mesa-libgl')
	depends=('amdgpu-core=18.50.725072-1' 'lib32-expat>=2.0.1' 'lib32-libomxil-bellagio' 'lib32-libva1' 'lib32-libvdpau' 'lib32-libx11' 'lib32-libx11>=1.4.99.1' 'lib32-libxcb' 'lib32-libxcb>=1.13' 'lib32-libxcb>=1.8' 'lib32-libxcb>=1.9.2' 'lib32-libxdamage' 'lib32-libxdamage>=1.1' 'lib32-libxext' 'lib32-libxfixes' 'lib32-libxshmfence' 'lib32-libxxf86vm' 'lib32-zlib>=1.1.4' 'libdrm-amdgpu=18.50.725072-1' 'libselinux>=1.32' 'llvm-amdgpu=18.50.725072-1' 'mesa-amdgpu=18.50.725072-1' 'systemd-libs' 'wayland-amdgpu=18.50.725072-1' 'xorgproto>=1.4.14' 'xorgproto>=2.6')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-mesa_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-mesa-drivers_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm-amdgpu-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu-pro_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu-pro-dev_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-dri_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-glx_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libglapi-amdgpu-mesa_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles1-amdgpu-mesa_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles1-amdgpu-mesa-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-mesa_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-mesa-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libosmesa6-amdgpu_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libosmesa6-amdgpu-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libxatracker-amdgpu-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libxatracker2-amdgpu_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-common-dev_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-omx-drivers_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-va-drivers_18.2.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-vdpau-drivers_18.2.0-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib32/
	mkdir -p "${pkgdir}"/usr/lib32/dri/
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1 "${pkgdir}"/usr/lib32/libvdpau_r300.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1.0 "${pkgdir}"/usr/lib32/libvdpau_r300.so.1.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1.0.0 "${pkgdir}"/usr/lib32/libvdpau_r300.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1 "${pkgdir}"/usr/lib32/libvdpau_r600.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1.0 "${pkgdir}"/usr/lib32/libvdpau_r600.so.1.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1.0.0 "${pkgdir}"/usr/lib32/libvdpau_r600.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1 "${pkgdir}"/usr/lib32/libvdpau_radeonsi.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0 "${pkgdir}"/usr/lib32/libvdpau_radeonsi.so.1.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0 "${pkgdir}"/usr/lib32/libvdpau_radeonsi.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/kms_swrast_dri.so "${pkgdir}"/usr/lib32/dri/kms_swrast_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/r200_dri.so "${pkgdir}"/usr/lib32/dri/r200_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/radeon_dri.so "${pkgdir}"/usr/lib32/dri/radeon_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/r300_dri.so "${pkgdir}"/usr/lib32/dri/r300_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/r600_dri.so "${pkgdir}"/usr/lib32/dri/r600_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/radeonsi_dri.so "${pkgdir}"/usr/lib32/dri/radeonsi_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/dri/swrast_dri.so "${pkgdir}"/usr/lib32/dri/swrast_dri.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libEGL.so.1 "${pkgdir}"/usr/lib32/libEGL.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libEGL.so.1.0.0 "${pkgdir}"/usr/lib32/libEGL.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGL.so "${pkgdir}"/usr/lib32/libGL.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGL.so.1 "${pkgdir}"/usr/lib32/libGL.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGL.so.1.2.0 "${pkgdir}"/usr/lib32/libGL.so.1.2.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libglapi.so.0 "${pkgdir}"/usr/lib32/libglapi.so.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libglapi.so.0.0.0 "${pkgdir}"/usr/lib32/libglapi.so.0.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGLESv1_CM.so.1 "${pkgdir}"/usr/lib32/libGLESv1_CM.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGLESv1_CM.so.1.1.0 "${pkgdir}"/usr/lib32/libGLESv1_CM.so.1.1.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGLESv2.so "${pkgdir}"/usr/lib32/libGLESv2.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGLESv2.so.2 "${pkgdir}"/usr/lib32/libGLESv2.so.2
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libGLESv2.so.2.0.0 "${pkgdir}"/usr/lib32/libGLESv2.so.2.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libOSMesa.so "${pkgdir}"/usr/lib32/libOSMesa.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libOSMesa.so.8 "${pkgdir}"/usr/lib32/libOSMesa.so.8
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libOSMesa.so.8.0.0 "${pkgdir}"/usr/lib32/libOSMesa.so.8.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libxatracker.so "${pkgdir}"/usr/lib32/libxatracker.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libxatracker.so.2 "${pkgdir}"/usr/lib32/libxatracker.so.2
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libxatracker.so.2.4.0 "${pkgdir}"/usr/lib32/libxatracker.so.2.4.0
	ln -s /opt/amdgpu/lib/libomxil-bellagio0/libomx_mesa.so "${pkgdir}"/usr/lib32/libomx_mesa.so

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-opencl-amdgpu () {
	pkgdesc="The AMDGPU Pro OpenCL implementation"
	arch=('x86_64')
	provides=('lib32-opencl-driver')
	depends=('amdgpu-pro-core=18.50.725072-1' 'lib32-gcc-libs')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./opencl-orca-amdgpu-pro-icd_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-opencl-orca-amdgpu () {
	pkgdesc="non-free AMD OpenCL ICD Loaders 32 bit"
	arch=('x86_64')
	depends=('amdgpu-pro-core=18.50.725072-1' 'lib32-glibc')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libopencl1-amdgpu-pro_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-vulkan-amdgpu () {
	pkgdesc="The AMDGPU Pro Vulkan driver 32bit"
	arch=('x86_64')
	provides=('lib32-vulkan-driver')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'lib32-gcc-libs' 'wsa-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./vulkan-amdgpu_18.50-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./vulkan-amdgpu-pro_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/share/vulkan/icd.d/
	mv "${pkgdir}"/opt/amdgpu/etc/vulkan/icd.d/amd_icd32.json "${pkgdir}"/usr/share/vulkan/icd.d/
	sed -i "s@abi_versions\(.*\)0.9.0\(.*\)@api_version\11.0.61\2@" "${pkgdir}"/usr/share/vulkan/icd.d/amd_icd32.json
	rm -rf "${pkgdir}"/opt/amdgpu/etc/vulkan/

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-wayland-amdgpu () {
	pkgdesc="Wayland compositor infrastructure 32 bit"
	arch=('x86_64')
	provides=('lib32-wayland')
	conflicts=('lib32-wayland')
	depends=('amdgpu-core=18.50.725072-1' 'lib32-expat>=2.0.1' 'lib32-libffi>=3.0.4' 'lib32-libxml2>=2.7.4' 'wayland-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-client0_1.15.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-cursor0_1.15.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-dev_1.15.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-egl1_1.15.0-725072_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-server0_1.15.0-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib32/
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-client.so "${pkgdir}"/usr/lib32/libwayland-client.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-client.so.0 "${pkgdir}"/usr/lib32/libwayland-client.so.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-client.so.0.3.0 "${pkgdir}"/usr/lib32/libwayland-client.so.0.3.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-cursor.so "${pkgdir}"/usr/lib32/libwayland-cursor.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-cursor.so.0 "${pkgdir}"/usr/lib32/libwayland-cursor.so.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-cursor.so.0.0.0 "${pkgdir}"/usr/lib32/libwayland-cursor.so.0.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-egl.so "${pkgdir}"/usr/lib32/libwayland-egl.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-egl.so.1 "${pkgdir}"/usr/lib32/libwayland-egl.so.1
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-egl.so.1.0.0 "${pkgdir}"/usr/lib32/libwayland-egl.so.1.0.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-server.so "${pkgdir}"/usr/lib32/libwayland-server.so
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-server.so.0 "${pkgdir}"/usr/lib32/libwayland-server.so.0
	ln -s /opt/amdgpu/lib/i386-linux-gnu/libwayland-server.so.0.1.0 "${pkgdir}"/usr/lib32/libwayland-server.so.0.1.0

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-wsa-amdgpu () {
	pkgdesc="Wayland support for AMD Vulkan driver 32 bit"
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'lib32-wayland' 'wayland-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./wsa-amdgpu_18.50-725072_i386.deb

	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_lib32-xserver-xorg-amdgpu-video-amdgpu () {
	pkgdesc="X.Org X server -- AMD/ATI Radeon display driver"
	arch=('x86_64')

	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var" "${pkgdir}"/opt/amdgpu-pro/{bin,include,share}
	rm -rf "${pkgdir}"/opt/amdgpu-pro/lib/xorg/modules/extensions/

}


package_libdrm-amdgpu () {
	pkgdesc="The AMDGPU Pro userspace interface to kernel DRM services"
	arch=('x86_64')
	provides=('libdrm')
	conflicts=('libdrm')
	depends=('amdgpu-core=18.50.725072-1' 'bcunit' 'cunit')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-amdgpu1_2.4.95-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-common_1.0.0-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-dev_2.4.95-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-radeon1_2.4.95-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm-amdgpu-utils_2.4.95-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libdrm2-amdgpu_2.4.95-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so "${pkgdir}"/usr/lib/libdrm.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2 "${pkgdir}"/usr/lib/libdrm.so.2
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0 "${pkgdir}"/usr/lib/libdrm.so.2.4.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libkms.so "${pkgdir}"/usr/lib/libkms.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libkms.so.1 "${pkgdir}"/usr/lib/libkms.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libkms.so.1.0.0 "${pkgdir}"/usr/lib/libkms.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so "${pkgdir}"/usr/lib/libdrm_amdgpu.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1 "${pkgdir}"/usr/lib/libdrm_amdgpu.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0 "${pkgdir}"/usr/lib/libdrm_amdgpu.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_radeon.so "${pkgdir}"/usr/lib/libdrm_radeon.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_radeon.so.1 "${pkgdir}"/usr/lib/libdrm_radeon.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1 "${pkgdir}"/usr/lib/libdrm_radeon.so.1.0.1
}


package_llvm-amdgpu () {
	pkgdesc="Generic buffer management API "
	arch=('x86_64')
	provides=('llvm-libs' 'llvm')
	conflicts=('llvm-libs' 'llvm')
	depends=('amdgpu-core=18.50.725072-1' 'binfmt-support' 'libedit' 'libedit>=2.11-20080614' 'libffi>=3.0.9' 'ncurses' 'ncurses5-compat-libs' 'ncurses5-compat-libs>=6' 'python2' 'zlib>=1.2.0')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libllvm7.0-amdgpu_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0-dev_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0-doc_7.0-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-7.0-runtime_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-dev_7.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./llvm-amdgpu-runtime_7.0-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/BugpointPasses.so "${pkgdir}"/usr/lib/BugpointPasses.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libLLVM-7.0.1.so "${pkgdir}"/usr/lib/libLLVM-7.0.1.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libLLVM-7.so "${pkgdir}"/usr/lib/libLLVM-7.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libLLVM.so "${pkgdir}"/usr/lib/libLLVM.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libLTO.so "${pkgdir}"/usr/lib/libLTO.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libLTO.so.7 "${pkgdir}"/usr/lib/libLTO.so.7
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/LLVMHello.so "${pkgdir}"/usr/lib/LLVMHello.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/TestPlugin.so "${pkgdir}"/usr/lib/TestPlugin.so
	ln -s /usr/lib/libedit.so "${pkgdir}"/usr/lib/libedit.so.2
}


package_mesa-amdgpu () {
	pkgdesc="Mesa implementation for AMDGPU Pro. Contains VDPAU video acceleration drivers: these libraries provide the Video Decode and Presentation API for Unix. They provide accelerated video playback (incl. H.264) and video post-processing for the supported graphics cards."
	arch=('x86_64')
	provides=('mesa-libgl' 'mesa-dri' 'opengl-driver' 'osmesa' 'mesa')
	conflicts=('mesa' 'mesa-vdpau' 'mesa-dri' 'mesa-libgl')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'expat>=2.0.1' 'libdrm-amdgpu=18.50.725072-1' 'libomxil-bellagio' 'libselinux>=1.32' 'libva1' 'libvdpau' 'libx11' 'libx11>=1.4.99.1' 'libxcb' 'libxcb>=1.13' 'libxcb>=1.8' 'libxcb>=1.9.2' 'libxdamage' 'libxdamage>=1.1' 'libxext' 'libxfixes' 'libxshmfence' 'libxxf86vm' 'llvm-amdgpu=18.50.725072-1' 'systemd-libs' 'wayland-amdgpu=18.50.725072-1' 'xorgproto>=1.4.14' 'xorgproto>=2.6' 'zlib>=1.1.4')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-mesa_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-mesa-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libegl1-amdgpu-mesa-drivers_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm-amdgpu-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu-pro-base_18.50-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgbm1-amdgpu-pro-dev_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-dri_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgl1-amdgpu-mesa-glx_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libglapi-amdgpu-mesa_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles1-amdgpu-mesa_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles1-amdgpu-mesa-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-mesa_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libgles2-amdgpu-mesa-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libosmesa6-amdgpu_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libosmesa6-amdgpu-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libxatracker-amdgpu-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libxatracker2-amdgpu_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-common-dev_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-omx-drivers_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-va-drivers_18.2.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./mesa-amdgpu-vdpau-drivers_18.2.0-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	mkdir -p "${pkgdir}"/usr/lib/dri/
	mkdir -p "${pkgdir}"/usr/lib/gbm/
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so.1 "${pkgdir}"/usr/lib/libvdpau_r300.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so.1.0 "${pkgdir}"/usr/lib/libvdpau_r300.so.1.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so.1.0.0 "${pkgdir}"/usr/lib/libvdpau_r300.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so.1 "${pkgdir}"/usr/lib/libvdpau_r600.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so.1.0 "${pkgdir}"/usr/lib/libvdpau_r600.so.1.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so.1.0.0 "${pkgdir}"/usr/lib/libvdpau_r600.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so.1 "${pkgdir}"/usr/lib/libvdpau_radeonsi.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0 "${pkgdir}"/usr/lib/libvdpau_radeonsi.so.1.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0 "${pkgdir}"/usr/lib/libvdpau_radeonsi.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so "${pkgdir}"/usr/lib/dri/kms_swrast_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/r200_dri.so "${pkgdir}"/usr/lib/dri/r200_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/r300_dri.so "${pkgdir}"/usr/lib/dri/r300_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/r600_dri.so "${pkgdir}"/usr/lib/dri/r600_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/radeon_dri.so "${pkgdir}"/usr/lib/dri/radeon_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/radeonsi_dri.so "${pkgdir}"/usr/lib/dri/radeonsi_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri/swrast_dri.so "${pkgdir}"/usr/lib/dri/swrast_dri.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so "${pkgdir}"/usr/lib/libEGL.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1 "${pkgdir}"/usr/lib/libEGL.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1.0.0 "${pkgdir}"/usr/lib/libEGL.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1 "${pkgdir}"/usr/lib/libGL.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGL.so.1.2.0 "${pkgdir}"/usr/lib/libGL.so.1.2.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libglapi.so.0 "${pkgdir}"/usr/lib/libglapi.so.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libglapi.so.0.0.0 "${pkgdir}"/usr/lib/libglapi.so.0.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGLESv1_CM.so.1 "${pkgdir}"/usr/lib/libGLESv1_CM.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGLESv1_CM.so.1.1.0 "${pkgdir}"/usr/lib/libGLESv1_CM.so.1.1.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGLESv2.so "${pkgdir}"/usr/lib/libGLESv2.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGLESv2.so.2 "${pkgdir}"/usr/lib/libGLESv2.so.2
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libGLESv2.so.2.0.0 "${pkgdir}"/usr/lib/libGLESv2.so.2.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libOSMesa.so "${pkgdir}"/usr/lib/libOSMesa.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libOSMesa.so.8 "${pkgdir}"/usr/lib/libOSMesa.so.8
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libOSMesa.so.8.0.0 "${pkgdir}"/usr/lib/libOSMesa.so.8.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libxatracker.so "${pkgdir}"/usr/lib/libxatracker.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libxatracker.so.2 "${pkgdir}"/usr/lib/libxatracker.so.2
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libxatracker.so.2.4.0 "${pkgdir}"/usr/lib/libxatracker.so.2.4.0
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libgbm.so  "${pkgdir}"/usr/lib/libgbm.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libgbm.so.1  "${pkgdir}"/usr/lib/libgbm.so.1
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libgbm.so.1.0.0  "${pkgdir}"/usr/lib/libgbm.so.1.0.0
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/gbm/gbm_amdgpu.so  "${pkgdir}"/usr/lib/gbm/gbm_amdgpu.so
	ln -s /opt/amdgpu/lib/libomxil-bellagio0/libomx_mesa.so "${pkgdir}"/usr/lib/libomx_mesa.so
	if [ -f /usr/lib/dri/i965_dri.so ] && [ "/usr/lib/dri" != "/opt/amdgpu/lib/x86_64-linux-gnu/dri" ]; then
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/dri "${pkgdir}"/usr/lib/dri/i965_dri.so
	fi
}


package_opencl-amdgpu () {
	pkgdesc="The AMDGPU Pro OpenCL implementation"
	arch=('x86_64')
	provides=('opencl-driver')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-dkms=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'libdrm-amdgpu=18.50.725072-1' 'numactl>=2.0.11' 'ocl-icd' 'opencl-orca-amdgpu=18.50.725072-1' 'pciutils>=3.5.2-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./clinfo-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./opencl-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./opencl-amdgpu-pro-dev_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./opencl-amdgpu-pro-icd_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./roct-amdgpu-pro_1.0.9-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./roct-amdgpu-pro-dev_1.0.9-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	mkdir -p "${pkgdir}"/usr/bin/
	ln -s /opt/amdgpu-pro/bin/clinfo "${pkgdir}"/usr/bin/clinfo
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so "${pkgdir}"/usr/lib/libamdocl64.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libcltrace.so "${pkgdir}"/usr/lib/libcltrace.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libhsakmt.so "${pkgdir}"/usr/lib/libhsakmt.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libhsakmt.so.1 "${pkgdir}"/usr/lib/libhsakmt.so.1
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libhsakmt.so.1.0.0 "${pkgdir}"/usr/lib/libhsakmt.so.1.0.0
}


package_opencl-orca-amdgpu () {
	pkgdesc="non-free AMD OpenCL ICD Loaders"
	arch=('x86_64')
	depends=('amdgpu-pro-core=18.50.725072-1' 'gcc-libs')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libopencl1-amdgpu-pro_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./opencl-orca-amdgpu-pro-icd_18.50-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so "${pkgdir}"/usr/lib/libamdocl-orca64.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so "${pkgdir}"/usr/lib/libamdocl12cl64.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so "${pkgdir}"/usr/lib/libOpenCL.so
	ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1 "${pkgdir}"/usr/lib/libOpenCL.so.1
}


package_vulkan-amdgpu () {
	pkgdesc="The AMDGPU Pro Vulkan driver"
	arch=('x86_64')
	provides=('vulkan-driver')
	depends=('amdgpu-core=18.50.725072-1' 'amdgpu-pro-core=18.50.725072-1' 'gcc-libs' 'wsa-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./vulkan-amdgpu_18.50-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./vulkan-amdgpu-pro_18.50-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/share/vulkan/icd.d/
	mv "${pkgdir}"/opt/amdgpu/etc/vulkan/icd.d/amd_icd64.json "${pkgdir}"/usr/share/vulkan/icd.d/
	sed -i "s@abi_versions\(.*\)0.9.0\(.*\)@api_version\11.0.61\2@" "${pkgdir}"/usr/share/vulkan/icd.d/amd_icd64.json
	rm -rf "${pkgdir}"/opt/amdgpu/etc/vulkan/
}


package_wayland-amdgpu () {
	pkgdesc="Wayland compositor infrastructure"
	arch=('x86_64')
	provides=('wayland')
	conflicts=('wayland')
	depends=('amdgpu-core=18.50.725072-1' 'expat>=2.0.1' 'libffi>=3.0.4' 'libxml2>=2.7.4')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-client0_1.15.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-cursor0_1.15.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-dev_1.15.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-doc_1.15.0-725072_all.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-egl1_1.15.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./libwayland-amdgpu-server0_1.15.0-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-client.so "${pkgdir}"/usr/lib/libwayland-client.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-client.so.0 "${pkgdir}"/usr/lib/libwayland-client.so.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0 "${pkgdir}"/usr/lib/libwayland-client.so.0.3.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-cursor.so "${pkgdir}"/usr/lib/libwayland-cursor.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-cursor.so.0 "${pkgdir}"/usr/lib/libwayland-cursor.so.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-cursor.so.0.0.0 "${pkgdir}"/usr/lib/libwayland-cursor.so.0.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-egl.so "${pkgdir}"/usr/lib/libwayland-egl.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-egl.so.1 "${pkgdir}"/usr/lib/libwayland-egl.so.1
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0 "${pkgdir}"/usr/lib/libwayland-egl.so.1.0.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-server.so "${pkgdir}"/usr/lib/libwayland-server.so
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-server.so.0 "${pkgdir}"/usr/lib/libwayland-server.so.0
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libwayland-server.so.0.1.0 "${pkgdir}"/usr/lib/libwayland-server.so.0.1.0
}


package_wayland-protocols-amdgpu () {
	pkgdesc="wayland compositor protocols"
	arch=('any')
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./wayland-protocols-amdgpu_1.16-725072_all.deb

	move_libdir "${pkgdir}/lib"

}


package_wsa-amdgpu () {
	pkgdesc="Wayland support for AMD Vulkan driver"
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'wayland-amdgpu' 'wayland-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./wsa-amdgpu_18.50-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/
	ln -s /opt/amdgpu/lib/x86_64-linux-gnu/libamdgpu_wsa_wayland.so "${pkgdir}"/usr/lib/libamdgpu_wsa_wayland.so
}


package_xf86-video-amdgpu-pro () {
	pkgdesc="The AMDGPU Pro X.org video driver"
	arch=('x86_64')
	provides=('xf86-video-amdgpu')
	conflicts=('xf86-video-amdgpu' 'xorg-server>=1.20.0' 'X-ABI-VIDEODRV_VERSION<23' 'X-ABI-VIDEODRV_VERSION>=24')
	groups=('xorg-drivers')
	depends=('amdgpu-core=18.50.725072-1' 'libdrm-amdgpu=18.50.725072-1' 'systemd-libs>=183' 'xserver-xorg-amdgpu=18.50.725072-1')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./xserver-xorg-amdgpu-video-amdgpu_18.1.99-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/xorg/modules/drivers/
	ln -s /opt/amdgpu/lib/xorg/modules/drivers/amdgpu_drv.so "${pkgdir}"/usr/lib/xorg/modules/drivers/amdgpu_drv.so
}


package_xserver-xorg-amdgpu () {
	pkgdesc="X.Org X server -- graphics acceleration module based on OpenGL. Glamor is a library for accelerating 2D graphics using GL functions. This package contains the X.Org module."
	arch=('x86_64')
	depends=('amdgpu-core=18.50.725072-1' 'libdrm-amdgpu=18.50.725072-1' 'libepoxy>=1.0')

	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./glamor-amdgpu_1.19.0-725072_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-18.50-725072-ubuntu-18.04/./glamor-amdgpu-dev_1.19.0-725072_amd64.deb

	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib/xorg/modules/
	ln -s /opt/amdgpu/lib/xorg/modules/libglamoregl.so "${pkgdir}"/usr/lib/xorg/modules/libglamoregl.so
}

